#!/usr/bin/env bash
#MISE description="Install all tools and configure git hooks"
set -euo pipefail

mise install --locked
MISE_ENV=development mise install --locked
MISE_ENV=development mise exec -- lefthook install
