#!/usr/bin/env bash
#MISE description="Run all linters"
set -euo pipefail

mise run check:markdown-format
mise run lint:actionlint
mise run lint:markdown
mise run lint:yamllint
mise run lint:tool-json
