name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: pretty-good-software-org/ci-shared/actions/setup/mise@v1
        with:
          mise-env: ci

      - name: Run linters
        run: mise run lint
